# from https://hub.docker.com/_/microsoft-vscode-devcontainers
FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-18.04
LABEL maintainer="matin03@gmail.com"
LABEL source="https://github.com/wbfw109/study-core/tree/dev/docker/Dockerfiles/unitree_ros_go_1_dev_env"