# from https://hub.docker.com/_/microsoft-vscode-devcontainers
FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-18.04
LABEL maintainer="matin03@gmail.com"
LABEL source="https://github.com/matin03/docker/tree/study/ubuntu/arm_18_04"

# settings
SHELL ["/bin/bash", "-c"]

RUN apt update -y
RUN apt upgrade -y

# Entrypoint
ENTRYPOINT ["/bin/bash"]
